sudo: required
services:
  - docker

before_install:
  - docker build -t oneryalcin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true oneryalcin/docker-react npm run test -- --watchAll=false
